name: e_learning_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  shared_preferences: ^2.3.3
  flutter_svg: ^2.0.17
  form_field_validator: ^1.1.0
  provider:
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  connectivity_plus: ^6.1.2
  firebase_messaging: ^15.2.0
  firebase_core: ^3.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
